import re
from collections import Counter
import os
from groq import Groq
from dotenv import load_dotenv

load_dotenv()
client = Groq(api_key=os.getenv("GROQ_API_KEY"))

def rule_based_findings(log_text: str) -> dict:
    findings = {
        "failed_login_count": 0,
        "unique_source_ips": [],
        "top_source_ips": [],
        "possible_bruteforce": False,
        "possible_sql_injection": False,
        "possible_port_scan": False,
        "notes": [],
    }

    text_lower = log_text.lower()

    failed_patterns = [
        r"failed password",
        r"authentication failure",
        r"invalid user",
        r"login failed",
    ]
    findings["failed_login_count"] = sum(len(re.findall(p, text_lower)) for p in failed_patterns)

    ips = re.findall(r"\b(?:\d{1,3}\.){3}\d{1,3}\b", log_text)
    ip_counts = Counter(ips)
    findings["unique_source_ips"] = sorted(list(set(ips)))
    findings["top_source_ips"] = [{"ip": ip, "count": count} for ip, count in ip_counts.most_common(5)]

    if findings["failed_login_count"] >= 8:
        findings["possible_bruteforce"] = True
        findings["notes"].append("High volume of failed login events suggests brute force or password spraying.")

    sqli_markers = ["union select", "or 1=1", "sleep(", "information_schema", "' or '1'='1"]
    if any(m in text_lower for m in sqli_markers):
        findings["possible_sql_injection"] = True
        findings["notes"].append("SQL injection indicators found in logs (keyword-based heuristic).")

    ports = re.findall(r"\bport\s+(\d{1,5})\b", text_lower)
    if len(set(ports)) >= 20:
        findings["possible_port_scan"] = True
        findings["notes"].append("Many distinct destination ports observed; possible scan activity.")

    return findings

def analyze_logs(log_text):
    rules = rule_based_findings(log_text)

    prompt = f"""
    Analyze these logs and extract:
    1. What type of attack or event occurred
    2. Which services or software are involved (e.g. SSH, Apache, Windows)
    3. Source IPs
    4. Key keywords I should search for in CVE databases

    RULE-BASED FINDINGS (Deterministic Heuristics):
    {rules}

    IMPORTANT:
    - These findings were generated by rule-based detection logic.
    - You must incorporate them into your final assessment.
    - If they suggest brute force, SQL injection, or scanning, explain why.

    Return your answer in clear labeled sections.

LOGS:
{log_text}
"""

    try:
        response = client.chat.completions.create(
            model=os.getenv("GROQ_MODEL", "llama-3.3-70b-versatile"),
            messages=[
                {"role": "system", "content": "You are a SOC analyst expert at reading system logs."},
                {"role": "user", "content": prompt}
            ]
        )
        return response.choices[0].message.content
    except Exception as e:
        return f"LLM log analysis failed: {str(e)}\n\nRULE-BASED FINDINGS:\n{rules}"